#!/bin/bash
#
# GIT version. Please do not edit this file.
# Make a copy and edit the copy.
#
# Maps: grid, example, cumberland, DISlabs
# Alg: RAND,CR,HCR,HPCC,CGG,MSP,GBS,SEBS,DTAG,DTAP
# Loc mode: odom, GPS
# Nav module: ros, thin_navigation
# Term: gnome-terminal,xterm
# Custom Stage flag: true, false

MAP=DISlabs
NROBOTS=8
ALG=DTAP
LOC=odom
NAV=ros
GWAIT=3
COMMDELAY=0.2
TERM=gnome-terminal 
TIMEOUT=1800
CUSTOM_STAGE=false

./start_experiment.py $MAP $NROBOTS $ALG $LOC $NAV $GWAIT $COMMDELAY $TERM $TIMEOUT $CUSTOM_STAGE

