#!/usr/bin/env python
#
# GIT version. Please do not edit this file.
# Make a copy and edit the copy.
#

import os

# Set here the experiments you want to analyze with ANOVA test

# D = <directory of the experiments>

# Example
D = '../results/cumberland_4/'

# L = <list of experiments to compare>

#Example
L = [
D+'DTAP/vaio-i7/20160117_175721',
D+'DTAP/vaio-i7/20160117_184032',
D+'DTAP/vaio-i7/20160117_192124'
]


# Run the R script

cmd = "Rscript anova_multi.R "

for i in range(0,len(L)):
  cmd = cmd + "%s_idleness.csv " %(L[i])

print cmd
os.system(cmd)

