#!/usr/bin/env python
#
# GIT version. Please do not edit this file.
# Make a copy and edit the copy.
#

import sys
import os


# L = <list of experiments to compare and label to use in the plot (no spaces allowed in the label!!!)>

L = []


# Read file with experiments to plot

if (len(sys.argv)<4):
    print "Use: do_boxplot_last_exp.py <num of last exp to plot> <plot title> <label_1> ... <label_n>"
    sys.exit(0)

exptoplot = "exptoplot.txt"
ntoplot = sys.argv[1]
cmd = "tail -n "+ntoplot+" experiments.txt > " + exptoplot
os.system(cmd)

plot_title = sys.argv[2]
outfile = '"'+plot_title+'.pdf"'

k = 3; # index for the labels

#print "File with exp to plot: ",exptoplot

f = open(exptoplot,'r')

for line in f:
    e = line.rstrip('\r\n ')
    L.append(e)
    L.append(sys.argv[k])
    k=k+1

f.close

# Run the R script

cmd = 'Rscript stats/boxplots.R "'+plot_title+'" '
lfiles = ""

for i in range(0,len(L)/2):
  lfiles = lfiles + "%s_idleness.csv %s " %(L[i*2],L[i*2+1])

print cmd+lfiles
os.system(cmd+lfiles)

cmd = 'mv Rplots.pdf '+outfile
os.system(cmd)

cmd = 'evince '+outfile+ ' &'
os.system(cmd)

